### ISSUE TITLE
Missing dependency for type-fest

### ISSUE THREAD

**Issue by nekoya** [mermaid-js/mermaid#6629]
### Description

I encountered the following error after upgrading ESLint to v9 using `npm init @eslint/config@latest`:

```
$ npx tsc --noemit --project .
node_modules/mermaid/dist/diagram-api/types.d.ts:2:34 - error TS2307: Cannot find module 'type-fest' or its corresponding type declarations.

2 import type { SetRequired } from 'type-fest';
                                   ~~~~~~~~~~~

Found 1 error in node_modules/mermaid/dist/diagram-api/types.d.ts:2
```

This upgrade also updated `globals` from version 13.24.0 to 16.2.0 in my node_modules.

In recent versions, `globals` has removed its dependency on type-fest:

https://github.com/sindresorhus/globals/pull/209/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L36-L38

As a workaround, I manually ran `npm i -D type-fest`, which resolved the error.

I suggest adding `type-fest` to devDependencies to prevent this issue.

### Steps to reproduce

1. Build the application with `globals` version 13.24.0
2. It works without errors
3. Upgrade `globals` to version 16.2.0
4. Build failed

### Code Sample

```text

```

### Setup

- Mermaid version: 11.6.0

### Suggested Solutions

- Add `type-fest` to devDependencies explicitly

### Additional Context

This issue likely occurs with globals version 14 and later.

https://github.com/sindresorhus/globals/releases/tag/v14.0.0

**Comment by knsv** [comment]
[sisyphus-bot] Thanks for the clear write-up! The missing `type-fest` dependency surfacing when other packages drop their transitive dependency on it is a valid packaging bug. The suggested fix of adding it explicitly to dependencies makes sense. Approved for work.

**Comment by ashishjain0512** [comment]
[sisyphus-bot]

**Fix Brief — Bot-Fixable Task**

This looks like a good candidate for an automated fix — queuing it up.

**Diagram type:** core
**Root cause:** `packages/mermaid/package.json` — The `SetRequired` type from `type-fest` is used in `dist/diagram-api/types.d.ts` but `type-fest` is only available as a transitive dependency via `globals`. When `globals` upgrades to v14+, `type-fest` is no longer available and the build breaks.
**Fix approach:** Add `type-fest` as a devDependency in the mermaid package.json with a version range matching what's currently resolved transitively.
**Affected files:**
- `packages/mermaid/package.json`

**Test strategy:** Verify `pnpm install` succeeds and the type import resolves. Run the build to confirm no type errors.
**Verification:** `pnpm install && pnpm --filter mermaid build`
**Constraints:**
- Only add the dependency — do not refactor type imports
- Draft PR targeting `develop`
- Include changeset (patch, fix: prefix)
- Link PR to #6629

**Comment by ashishjain0512** [comment]
[sisyphus-bot] Draft PR created: #7433. Awaiting review.
