### ISSUE TITLE
Unable to compile with mermaid 11.4.1

### ISSUE THREAD

**Issue by kevin-james-sp** [mermaid-js/mermaid#6107]
### Description

Upgraded a project using mermaid 10.9.3 to mermaid 11.4.1. It then refused to compile with the following error:
```
node_modules/@antfu/utils/dist/index.d.ts:591:5 - error TS2416: Property 'then' in type 'PInstance<T>' is not assignable to the same property in base type 'Promise<Awaited<T>[]>'.
  Type '(fn?: () => PromiseLike<any>) => Promise<any>' is not assignable to type '<TResult1 = Awaited<T>[], TResult2 = never>(onfulfilled?: (value: Awaited<T>[]) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<...>) => Promise<...>'.
    Types of parameters 'fn' and 'onfulfilled' are incompatible.
      Target signature provides too few arguments. Expected 1 or more, but got 0.

591     then(fn?: () => PromiseLike<any>): Promise<any>;
        ~~~~
```
Unable to find the problem, I created a simple test case. Maybe I'm using the wrong version of something somewhere.

### Steps to reproduce

Node v20.17.0
package.json
```
{
  "name": "mermaidtest",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "mermaid": "^11.4.1"
  },
  "type": "module",
  "devDependencies": {
    "@types/node": "^20.12.10",
    "ts-jest": "^29.2.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.7.2"
  }
}
```
test.ts
```
import mermaid from "mermaid";

console.log('end');
```
After running `npm i`, Running `npx tsc test.ts` give the same error as above.

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by kut** [comment]
I get the same in v11.4.0

**Comment by long-long-float** [comment]
We can avoid the error in v11.3.0 too.

**Comment by Xorok** [comment]
This issue persists in the latest version 11.4.1. It was introduced in v11.2.0.

Downgrading to the version before v11.2.0 (= v11.1.10) is also not possible since it doesn't compile because of issue #5747 which was introduced in v11.0.0. So the latest version that compiles is 10.9.3, which should not be used as it depends on `"dompurify": "^3.0.5 <3.1.7"`, which now has security vulnerabilities: https://github.com/advisories/GHSA-vhxf-7vqr-mrjg

As a temporary workaround, the errors from both this issue and issue #5747 can be ignored by setting `"skipLibCheck": true` in the `"compilerOptions"` in tsconfig.json, then it compiles.

It would be great if library releases were tested without `"skipLibCheck"` or similar options in the testing environment in the future... :/

**Comment by moddx** [comment]
This is still a problem in v11.9.0. I know it's technically a problem in @antfu/utils, but ..

**Comment by moddx** [comment]
I tried overruling the resolution in yarn with @antfu/utils@9.2.0, and that seems to work so far.

**Comment by knsv** [comment]
[sisyphus-bot]

Thanks for the detailed reproduction and investigation, and apologies for the delay!

The transitive dependency `@antfu/utils` ships TypeScript types that are incompatible under `skipLibCheck: false`. As you found, overriding to v9.2.0 resolves it. The fix on our side is to pin or update this transitive dependency so consumers don't hit this issue.

Tagging for contributors.
