### ISSUE TITLE
Mermaid 9.2.0 fails to require properly with Webpack

### ISSUE THREAD

**Issue by sgerace** [mermaid-js/mermaid#3754]
### Description

We've been using Mermaid without issue for some time now and the latest version (9.2.0) breaks our application. We're utilizing webpack to bundle our application and requiring and initializing mermaid with:
```javascript
// Initialize mermaid renderer
const mermaid = require('mermaid');
mermaid.initialize({
    startOnLoad: false
});
```
After updating to 9.2.0, we are getting the following warnings from webpack:
```
WARNING in ./node_modules/mermaid/dist/mermaid.min.js 1277:3945-3954
Critical dependency: the request of a dependency is an expression
```
And `mermaid.initialize` fails with the following error in the browser:
```
Uncaught TypeError: mermaid.initialize is not a function
```

It seems like there may have been changes to the bundled artifact as part of the 9.2.0 release, however, I would not expected any breaking changes as a result of a minor version change.

### Steps to reproduce

Require Mermaid 9.2.0 with Webpack using CommonJS syntax.

### Setup

**Desktop**

- OS and Version: Mac
- Browser and Version: Chrome

**Comment by sidharthv96** [comment]
We are doing a lazy load internally, wonder if it's related.

https://stackoverflow.com/a/73359606/2212355

**Comment by sidharthv96** [comment]
Can you please test `9.2.2-rc.2`

**Comment by sidharthv96** [comment]
Fixed in 9.2.2

**Comment by sgerace** [comment]
Hi @sidharthv96, sorry I wasn't able to confirm the fix yesterday. I can confirm that the fixed published in 9.2.2 does indeed fix the issue for us. Thanks!
