### ISSUE TITLE
Mermaid 11.17.0 fails when a global `define` function exists

### ISSUE THREAD

**Issue by bscan** [mermaid-js/mermaid#8095]
### Description

Mermaid 11.17.0 fails to initialize when the page already has a global `define` function. The same example works with 11.16.1.

With Mermaid 11.17.0, the console reports:

```text
Uncaught TypeError: Wae.default.extend is not a function
```
and `window.mermaid` is undefined. Changing only the Mermaid version to `11.16.1` makes the example work as expected.

### Steps to reproduce

This fails, while changing 11.17.0 -> 11.16.1 works
```html
<!doctype html>
<html>
<body>
  <script>
    function define() {}
  </script>

  <script src="https://cdn.jsdelivr.net/npm/mermaid@11.17.0/dist/mermaid.min.js"></script>

  <pre class="mermaid">
graph TD
  A --> B
  </pre>
</body>
</html>
```

### Code Sample

```text

```

### Setup

- Mermaid version: 11.17.0
- Browser and Version: Chrome and vscode embedded browser

### Suggested Solutions

Ensure bundled dependencies such as FastDom do not detect or register with a global AMD define function when loaded as part of mermaid.min.js. This may require adjusting the bundle configuration or how the FastDom dependency is wrapped/imported.
