### ISSUE TITLE
Flowchart click events with function names do not work in mermaid 8.4.6

### ISSUE THREAD

**Issue by GDFaber** [mermaid-js/mermaid#1220]
**Describe the bug**
Click events don't seem to work anymore in mermaid 8.4.6; when I tested the interaction example from the docs in the live editor, I got the error `Uncaught TypeError: window[t] is not a function at SVGGElement.<anonymous> (bundle.js:72)` when clicking on the left node.

**To Reproduce**
1. [Go to live-editor example](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFI7XG4gICAgQS0tPkI7XG4gICAgY2xpY2sgQSBjYWxsYmFjayBcIlRvb2x0aXAgZm9yIGEgY2FsbGJhY2tcIlxuICAgIGNsaWNrIEIgXCJodHRwOi8vd3d3LmdpdGh1Yi5jb21cIiBcIlRoaXMgaXMgYSB0b29sdGlwIGZvciBhIGxpbmtcIiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0Iiwic2VjdXJpdHlMZXZlbCI6Imxvb3NlIn19)
2. Click on the left node
3. Open developer tools in browser
4. See error message in console

**Expected behavior**
Clicking the node should trigger function call.

**Comment by GDFaber** [comment]
After fiddling with dist/index.html some more, it turned out that the click events work for flowcharts as well as for gantt. I found out by removing everything else from the file and testing only one flowchart/gantt diagram.

However, the flowchart click events don't work if I leave the file as it is (except setting `securityLevel: 'loose'`). I'm going to investigate this further, but I guess this issue can be closed as a false alarm.
